### ISSUE TITLE
Missing comma from local_dev settings

### ISSUE THREAD

**Issue by ginestra** [kingsdigitallab/django-bare-bones#9]
* Django KDL Wagtail version: 0.6.6
* Django version: 2.1.7
* Python version: 3.5
* Operating System: N/A

### Description

The local_dev setting file is missing a comma in the list of ALLOWED_HOSTS

```
ALLOWED_HOSTS = ['127.0.0.1',
                 'localhost'
                 '[::1]',
                 'ego-dev.kdl.kcl.ac.uk']
```

**Comment by brian-maher** [comment]
Fixed in ab2ba84
